spring:
 application:
  name: customer-service

server:
 port: ${app_port}

eureka:
 client:
  serviceURL:
   defaultZone: http://localhost:8761/eureka
#   defaultZone: http://localhost:8901/eureka,http://localhost:8902/eureka


management:
 tracing:
  enabled: true
  sampling:
   probability: 1.0
 zipkin:
  tracing:
   endpoint: http://localhost:9411/api/v2/spans