spring:
 application:
 name: discovery-server

server:
 port: 8761
eureka:
 client:
  register-with-eureka: false
  fetch-registry: false
 server:
  enable-self-preservation: false

endpoints:
 enabled: true
 sensitive: false

management:
 endpoints:
  web:
   exposure:
    include: "*"
 tracing:
  enabled: true
  sampling:
   probability: 1.0
 zipkin:
  tracing:
   endpoint: http://localhost:9411/api/v2/spans

