spring:
 application:
  name: restaurant-service-gateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   routes:
    - id: customers
      uri: lb://customer-service
      predicates:
      - Path=/customer/**
    - id: restaurants
      uri: lb://restaurant-service
      predicates:
      - Path=/restaurant/**

server:
 port: ${app_port}

eureka:
 client:
  serviceURL:
   defaultZone: http://localhost:8761/eureka
#   defaultZone: http://localhost:8901/eureka,http://localhost:8902/eureka


management:
 endpoint:
  gateway:
   enabled: true

 endpoints:
  web:
   exposure:
    include: gateway
 
 tracing:
  enabled: true
  sampling:
   probability: 1.0
 zipkin:
  tracing:
   endpoint: http://localhost:9411/api/v2/spans
